---

- name: Activate DoS Protection service
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/cm/security-shared/tasks/add-dos-listener"
    timeout: "{{ register_dcd_cm_timeout }}"
    validate_certs: "{{ register_dcd_cm_validate_certs }}"
    method: POST
    body:
      module: dos
      listenerInterfaceAddress: "{{ register_dcd_dcd_listener }}"
      deviceReference:
        link: "{{ device_ref }}"
    body_format: json
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
    status_code: 200,202
  register: r
  changed_when: r.status in [200, 202]
  until: r.status in [200, 202]
  retries: 120
  delay: 2

- name: Set task ID
  set_fact:
    task_id: "{{ r.json.id }}"

- name: Wait for DoS Protection service activation to complete
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/cm/security-shared/tasks/add-dos-listener/{{ task_id }}"
    timeout: "{{ register_dcd_cm_timeout }}"
    validate_certs: "{{ register_dcd_cm_validate_certs }}"
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
  register: r
  changed_when: r.status == 200
  retries: 120
  until: r.json.status in ['FINISHED', 'FAILED'] or r.status == 404
  delay: 2

- name: Fail if DoS Protection service activation failed
  fail:
    msg: "DoS Protection service activation failed with: {{ r.json.errorMessage }}"
  when: r.json.status == 'FAILED'
