---

- name: Setup provider to connect to CM device
  set_fact:
    provider:
      server: "{{ register_dcd_cm_server }}"
      server_port: "{{ register_dcd_cm_server_port }}"
      user: "{{ register_dcd_cm_user }}"
      password: "{{ register_dcd_cm_password }}"
      validate_certs: "{{ register_dcd_cm_validate_certs }}"
      transport: "{{ register_dcd_cm_transport }}"

- name: Wait for BIG-IQ to be available
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/info/system"
    timeout: "{{ register_dcd_cm_timeout }}"
    validate_certs: "{{ register_dcd_cm_validate_certs }}"
  register: status
  until: status is success and status.json.available|bool
  retries: 10
  delay: 6

- name: Get authentication token
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/shared/authn/login"
    method: POST
    timeout: "{{ register_dcd_cm_timeout }}"
    validate_certs: "{{ register_dcd_cm_validate_certs }}"
    body:
      username: "{{ provider.user }}"
      password: "{{ provider.password }}"
    body_format: json
  register: r

- name: Set the token fact if authentication succeeded
  set_fact:
    f5_auth_token: "{{ r.json.token.token }}"
  when: r is success

- name: Test authentication
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/shared/echo"
    timeout: "{{ register_dcd_cm_timeout }}"
    validate_certs: "{{ register_dcd_cm_validate_certs }}"
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
  register: status

- name: Get device provisioning type
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/cm/system/provisioning"
    timeout: "{{ register_dcd_cm_timeout }}"
    validate_certs: "{{ register_dcd_cm_validate_certs }}"
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
  register: r

- name: Fail if you're running the role against a DCD device
  fail:
    msg: "This role should be run against a CM device, but you appear to be running it against a DCD device"
  when: r.json.systemPersonality == 'logging_node'

- name: Check if system is setup
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/shared/system/setup"
    timeout: "{{ register_dcd_cm_timeout }}"
    validate_certs: "{{ register_dcd_cm_validate_certs }}"
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
  register: setup

- name: Stop if the system is not setup
  fail:
    msg: "The DCD device has not been setup. Please onboard the DCD device first."
  when: setup.json.isSystemSetup is not defined or not setup.json.isSystemSetup|bool

- name: Ensure the DCD server IP address is provided
  fail:
    msg: "Please change the register_dcd_dcd_server variable to be the IP address of the DCD device."
  when: register_dcd_dcd_server == 'localhost'

- name: Set the listener if it is not specified
  set_fact:
    register_dcd_dcd_listener: "{{ register_dcd_dcd_server }}"
  when: register_dcd_dcd_listener == 'localhost'

- name: Check that device is not already registered
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/shared/resolver/device-groups/cm-esmgmt-logging-group/devices"
    timeout: "{{ register_dcd_cm_timeout }}"
    validate_certs: "{{ register_dcd_cm_validate_certs }}"
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
  register: setup

- name: Get devices from CM
  set_fact:
    devices: "{{ setup.json | json_query('items[*].address') }}"

- import_tasks: setup-dcd-device.yaml
  when: register_dcd_dcd_server not in devices

- name: Get DCD Device Reference
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/shared/resolver/device-groups/cm-esmgmt-logging-group/devices/?$select=selfLink,properties&$filter=address+eq+'{{ register_dcd_dcd_server }}'"
    timeout: "{{ register_dcd_cm_timeout }}"
    validate_certs: "{{ register_dcd_cm_validate_certs }}"
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
  register: r

- name: Ensure that there is only one result
  assert:
    that:
      - r.json.totalItems|default(0) == 1

- name: Set the device reference fact
  set_fact:
    device_ref: "{{ r.json['items'][0].selfLink }}"
    device_id: "{{ r.json['items'][0].selfLink|basename }}"
    has_afm_service: "{{ 'cm:afm:logging:module' in r.json['items'][0].properties }}"
    has_access_service: "{{ 'cm:access:logging:module' in r.json['items'][0].properties }}"
    has_dos_service: "{{ 'cm:dos:logging:module' in r.json['items'][0].properties }}"
    has_websafe_service: "{{ 'cm:websafe:logging:module' in r.json['items'][0].properties }}"
    has_ipsec_service: "{{ 'cm:ipsec:logging:module' in r.json['items'][0].properties }}"
    has_asm_service: "{{ 'cm:asm:logging:module' in r.json['items'][0].properties }}"

- include_tasks: activate-service-access.yaml
  when:
    - "'access' in register_dcd_dcd_services"
    - not has_access_service|bool

- include_tasks: deactivate-service-access.yaml
  when:
    - "'access' not in register_dcd_dcd_services"
    - has_access_service|bool

- include_tasks: activate-service-afm.yaml
  when:
    - "'afm' in register_dcd_dcd_services"
    - not has_afm_service|bool

- include_tasks: deactivate-service-afm.yaml
  when:
    - "'afm' not in register_dcd_dcd_services"
    - has_afm_service|bool

- include_tasks: activate-service-asm.yaml
  when:
    - "'asm' in register_dcd_dcd_services"
    - not has_asm_service|bool

- include_tasks: deactivate-service-asm.yaml
  when:
    - "'asm' not in register_dcd_dcd_services"
    - has_asm_service|bool

- include_tasks: activate-service-dos.yaml
  when:
    - "'dos' in register_dcd_dcd_services"
    - not has_dos_service|bool

- include_tasks: deactivate-service-dos.yaml
  when:
    - "'dos' not in register_dcd_dcd_services"
    - has_dos_service|bool

- include_tasks: activate-service-ipsec.yaml
  when:
    - "'ipsec' in register_dcd_dcd_services"
    - not has_ipsec_service|bool

- include_tasks: deactivate-service-ipsec.yaml
  when:
    - "'ipsec' not in register_dcd_dcd_services"
    - has_ipsec_service|bool

- include_tasks: activate-service-websafe.yaml
  when:
    - "'websafe' in register_dcd_dcd_services"
    - not has_websafe_service|bool

- include_tasks: deactivate-service-websafe.yaml
  when:
    - "'websafe' not in register_dcd_dcd_services"
    - has_websafe_service|bool
