---

- name: Onboard all devices
  hosts: all
  roles:
    - role: bigiq-onboard

- name: Add DCD devices to CM device concurrently
  hosts: dcd
  tasks:
    - name: Add DCD to CM
      include_role:
        name: ansible-role-register_dcd
      vars:
        register_dcd_dcd_server: "{{ bigiq_onboard_server }}"
